# Generated by Django 4.0 on 2022-01-04 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='log',
            new_name='logo',
        ),
    ]
